spring.application.name=ms-catalog
server.port=8082
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}
spring.config.import=optional:file:.env[.properties]
management.endpoints.web.exposure.include=health

# Datasource Configuration
spring.datasource.url=${CATALOG_DATABASE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA Configuration
spring.jpa.hibernate.ddl-auto=${JPA_CONFIG_DDL:validate}
spring.jpa.show-sql=${JPA_CONFIG_SHOW_SQL:false}
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Documentation Configuration (Swagger/OpenAPI)
springdoc.api-docs.enabled=${UI_DOCUMENTATION_ENABLE:false}
springdoc.swagger-ui.enabled=${UI_DOCUMENTATION_ENABLE:false}
springdoc.api-docs.version=OPENAPI_3_1

# Cache
cache.hotel.enabled=true
cache.hotel.ttl-minutes=10
cache.hotel.max-size=500
