name: hotel-reservation-app

services:
  postgres-datasource:
    image: postgres:18.3
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      AUTH_DATABASE_NAME: ${AUTH_DATABASE_NAME}
      CATALOG_DATABASE_NAME: ${CATALOG_DATABASE_NAME}
      BOOKING_DATABASE_NAME: ${BOOKING_DATABASE_NAME}
      AVAILABILITY_DATABASE_NAME: ${AVAILABILITY_DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./hotel-reservation-data:/var/lib/postgresql
      - ./config/database/init.sh:/docker-entrypoint-initdb.d/init.sh
    restart: always
    networks:
      - hotel-reservation-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - hotel-reservation-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - hotel-reservation-network

  redis:
    image: redis:8.6.2-alpine
    ports:
      - "6379:6379"
    restart: always
    networks:
      - hotel-reservation-network

  ms-gateway:
    build:
      context: ./ms-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      UI_DOCUMENTATION_ENABLE: ${UI_DOCUMENTATION_ENABLE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      GATEWAY_REPLENISH_RATE: ${GATEWAY_REPLENISH_RATE}
      GATEWAY_BURST_CAPACITY: ${GATEWAY_BURST_CAPACITY}
      GATEWAY_REQUEST_TOKEN: ${GATEWAY_REQUEST_TOKEN}
      GATEWAY_CONNECT_TIMEOUT: ${GATEWAY_CONNECT_TIMEOUT}
      GATEWAY_RESPONSE_TIMEOUT: ${GATEWAY_RESPONSE_TIMEOUT}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      AGENT_SERVICE_URL: ${AGENT_SERVICE_URL}
      AVAILABILITY_SERVICE_URL: ${AVAILABILITY_SERVICE_URL}
      BOOKING_SERVICE_URL: ${BOOKING_SERVICE_URL}
      CATALOG_SERVICE_URL: ${CATALOG_SERVICE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_TOKEN_TYPE: ${JWT_TOKEN_TYPE}
      GATEWAY_ALLOWED_METHODS: ${GATEWAY_ALLOWED_METHODS}
      GATEWAY_ALLOWED_ORIGINS: ${GATEWAY_ALLOWED_ORIGINS}
      GATEWAY_MAX_AGE: ${GATEWAY_MAX_AGE}

    restart: on-failure
    networks:
      - hotel-reservation-network

  ms-auth:
    build:
      context: ./ms-auth
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres-datasource
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      AUTH_DATASOURCE_URL: jdbc:postgresql://postgres-datasource:5432/${AUTH_DATABASE_NAME}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      JPA_CONFIG_DDL: ${JPA_CONFIG_DDL}
      UI_DOCUMENTATION_ENABLE: ${UI_DOCUMENTATION_ENABLE}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      JWT_TOKEN_TYPE: ${JWT_TOKEN_TYPE}

    restart: on-failure
    networks:
      - hotel-reservation-network

  ms-catalog:
    build:
      context: ./ms-catalog
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres-datasource
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      CATALOG_DATASOURCE_URL: jdbc:postgresql://postgres-datasource:5432/${CATALOG_DATABASE_NAME}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      JPA_CONFIG_DDL: ${JPA_CONFIG_DDL}
      UI_DOCUMENTATION_ENABLE: ${UI_DOCUMENTATION_ENABLE}
      HOTEL_CATALOG_CACHE_ENABLED: ${HOTEL_CATALOG_CACHE_ENABLED}
      HOTEL_CATALOG_CACHE_TTL_MINUTES: ${HOTEL_CATALOG_CACHE_TTL_MINUTES}
      HOTEL_CATALOG_CACHE_MAX_SIZE: ${HOTEL_CATALOG_CACHE_MAX_SIZE}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    restart: on-failure
    networks:
      - hotel-reservation-network

  ms-booking:
    build:
      context: ./ms-booking
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - postgres-datasource
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      BOOKING_DATASOURCE_URL: jdbc:postgresql://postgres-datasource:5432/${BOOKING_DATABASE_NAME}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      JPA_CONFIG_DDL: ${JPA_CONFIG_DDL}
      UI_DOCUMENTATION_ENABLE: ${UI_DOCUMENTATION_ENABLE}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      CATALOG_SERVICE_URL: ${CATALOG_SERVICE_URL}
      AVAILABILITY_SERVICE_URL: ${AVAILABILITY_SERVICE_URL}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}

    restart: on-failure
    networks:
      - hotel-reservation-network

  ms-availability:
    build:
      context: ./ms-availability
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - postgres-datasource
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      AVAILABILITY_DATASOURCE_URL: jdbc:postgresql://postgres-datasource:5432/${AVAILABILITY_DATABASE_NAME}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      JPA_CONFIG_DDL: ${JPA_CONFIG_DDL}
      UI_DOCUMENTATION_ENABLE: ${UI_DOCUMENTATION_ENABLE}
    restart: on-failure
    networks:
      - hotel-reservation-network

  ms-notification:
    build:
      context: ./ms-notification
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      UI_DOCUMENTATION_ENABLE: ${UI_DOCUMENTATION_ENABLE}
    restart: on-failure
    networks:
      - hotel-reservation-network

  ms-agent:
    build:
      context: ./ms-agent
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      UI_DOCUMENTATION_ENABLE: ${UI_DOCUMENTATION_ENABLE}
    restart: on-failure
    networks:
      - hotel-reservation-network

networks:
  hotel-reservation-network:
    driver: bridge