spring.application.name=ms-gateway
server.port=8080
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}
spring.config.import=optional:file:.env[.properties]
management.endpoints.web.exposure.include=health

# Redis Configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# Gateway Configuration
spring.cloud.gateway.server.webflux.httpclient.connect-timeout=${GATEWAY_CONNECT_TIMEOUT:3000}
spring.cloud.gateway.server.webflux.httpclient.response-timeout=${GATEWAY_RESPONSE_TIMEOUT:5s}

# Gateway Services
hotel.gateway.service.auth=${AUTH_SERVICE_URL}
hotel.gateway.service.agent=${AGENT_SERVICE_URL}
hotel.gateway.service.availability=${AVAILABILITY_SERVICE_URL}
hotel.gateway.service.booking=${BOOKING_SERVICE_URL}
hotel.gateway.service.catalog=${CATALOG_SERVICE_URL}

#Gateway JWT
hotel.gateway.jwt.secret=${JWT_SECRET}
hotel.gateway.jwt.token-prefix=${JWT_TOKEN_TYPE:Bearer}

# Cors Configuration
hotel.gateway.cors.allowed-methods=${GATEWAY_ALLOWED_METHODS}
hotel.gateway.cors.allowed-origins=${GATEWAY_ALLOWED_ORIGINS}
hotel.gateway.cors.max-age=${GATEWAY_MAX_AGE:3600}

# Documentation Configuration (Swagger/OpenAPI)
springdoc.api-docs.enabled=${UI_DOCUMENTATION_ENABLE:false}
springdoc.swagger-ui.enabled=${UI_DOCUMENTATION_ENABLE:false}
springdoc.api-docs.version=OPENAPI_3_1